version: "3.8"
services:
  mysql:
    image: docker.io/bitnami/mysql:5.7.36
    environment:
      - MYSQL_ROOT_PASSWORD=lulw
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - chat-cluster
  rabbitmq:
    image: docker.io/bitnami/rabbitmq
    environment:
      - RABBITMQ_USERNAME=openstack
      - RABBITMQ_PASSWORD=openstack
    networks:
      - chat-cluster
  redis:
    image: docker.io/bitnami/redis
    networks:
      - chat-cluster
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  designate-mdns:
    hostname: designate-mdns
    image: docker.io/kolla/ubuntu-binary-designate-mdns:xena
    volumes:
      - ./openstack-components/designate/mdns:/var/lib/kolla/config_files/mdns
      - ./openstack-components/designate/conf:/var/lib/kolla/config_files/conf
    environment:
      - KOLLA_CONFIG_STRATEGY=COPY_ONCE
      - KOLLA_CONFIG_FILE=/var/lib/kolla/config_files/mdns/config.json
    networks:
      - chat-cluster
    depends_on:
      - mysql
      - rabbitmq
  designate-worker:
    image: docker.io/kolla/ubuntu-binary-designate-worker:xena
    volumes:
      - ./openstack-components/designate/worker:/var/lib/kolla/config_files/worker
      - ./openstack-components/designate/conf:/var/lib/kolla/config_files/conf
      - ./openstack-components/designate/bind:/var/lib/kolla/secret
    environment:
      - KOLLA_CONFIG_STRATEGY=COPY_ONCE
      - KOLLA_CONFIG_FILE=/var/lib/kolla/config_files/worker/config.json
    networks:
      - chat-cluster
    depends_on:
      - mysql
      - rabbitmq
  designate-producer:
    image: docker.io/kolla/ubuntu-binary-designate-producer:xena
    volumes:
      - ./openstack-components/designate/producer:/var/lib/kolla/config_files/producer
      - ./openstack-components/designate/conf:/var/lib/kolla/config_files/conf
    environment:
      - KOLLA_CONFIG_STRATEGY=COPY_ONCE
      - KOLLA_CONFIG_FILE=/var/lib/kolla/config_files/producer/config.json
    networks:
      - chat-cluster
    depends_on:
      - mysql
      - rabbitmq
  designate-central:
    image: docker.io/kolla/ubuntu-binary-designate-central:xena
    volumes:
      - ./openstack-components/designate/central:/var/lib/kolla/config_files/central
      - ./openstack-components/designate/conf:/var/lib/kolla/config_files/conf
      - ./openstack-components/designate/manager:/var/lib/kolla/config_files/manager
    environment:
      - KOLLA_CONFIG_STRATEGY=COPY_ONCE
      - KOLLA_CONFIG_FILE=/var/lib/kolla/config_files/central/config.json
    networks:
      - chat-cluster
    depends_on:
      - mysql
      - rabbitmq
  designate-api:
    image: docker.io/kolla/ubuntu-binary-designate-api:xena
    volumes:
      - ./openstack-components/designate/api:/var/lib/kolla/config_files/api
      - ./openstack-components/designate/conf:/var/lib/kolla/config_files/conf
    environment:
      - KOLLA_CONFIG_STRATEGY=COPY_ONCE
      - KOLLA_CONFIG_FILE=/var/lib/kolla/config_files/api/config.json
    networks:
      - chat-cluster
    depends_on:
      - mysql
      - rabbitmq
  bind:
    domainname: ns1.chat-cluster.com
    image: docker.io/internetsystemsconsortium/bind9:9.17
    volumes:
      - ./openstack-components/designate/bind:/etc/bind/
    networks:
      - chat-cluster
    command: ["/usr/sbin/named", "-g", "-d", "9", "-c", "/etc/bind/named.conf", "-u", "bind"]
    ports:
      - 127.0.0.53:53:53/udp
  keystone:
    hostname: keystone
    image: docker.io/kolla/ubuntu-binary-keystone:xena
    volumes:
      - ./openstack-components/keystone:/var/lib/kolla/config_files
    environment:
      - KOLLA_CONFIG_STRATEGY=COPY_ONCE
      - KOLLA_CONFIG_FILE=/var/lib/kolla/config_files/config.json
      - KEYSTONE_ADMIN_PASSWORD=keystoneAdmin
    networks:
      - chat-cluster
    depends_on:
      - mysql
    ports:
      # admin
      - 5000:5000
      # public
      - 5001:5001
  keycloak:
    networks:
      - chat-cluster
    build:
      context: keycloak/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=mysql
      - DB_ADDR=mysql
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    ports:
      - "8443:8443"
    volumes:
      - ./keycloak/startup-scripts:/tmp/scripts
    depends_on:
      - mysql
networks:
  chat-cluster:
    name: "chat-cluster"
    external: true
