kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: "chat-cluster"
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: keycloak/secrets
        containerPath: /etc/ssl/certs/keycloak
    #extraPortMappings:
    #  - containerPort: 30080
    #    hostPort: 80
    #  - containerPort: 30443
    #    hostPort: 443
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            oidc-issuer-url: "https://keycloak:8443/auth/realms/kubernetes"
            oidc-client-id: "kubernetes"
            oidc-ca-file: "/etc/ssl/certs/keycloak/ca.pem"
            oidc-username-claim: "email"
