version: "3.8"
services:
  keycloak:
    networks:
      - kind
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_USER=admin
      #- KEYCLOAK_IMPORT=kubernetes.json
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=postgres
      - DB_ADDR=postgres:5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    ports:
      - "8443:8443"
    volumes:
      #- ./realms/:/tmp
      - ./startup-scripts:/tmp/scripts
    depends_on:
      - postgres

  postgres:
    networks:
      - kind
    image: bitnami/postgresql:13
    environment:
      - POSTGRESQL_DATABASE=keycloak
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=keycloak

networks:
  kind: null
