version: "3.8"
services:
  # redis:
  #   image: bitnami/redis
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   networks:
  #     - designate

  mysql:
    image: bitnami/mysql:5.7.36
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=designate
      - MYSQL_PASSWORD=designate
      - MYSQL_DATABASE=designate
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    networks:
      - designate

  rabbitmq:
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_USERNAME=designate
      - RABBITMQ_PASSWORD=designate
    networks:
      - designate

  designate-mdns:
    image: kolla/ubuntu-binary-designate-mdns:victoria
    volumes:
      - ./mdns:/var/lib/kolla/config_files/mdns/
      - ./conf:/var/lib/kolla/config_files/
    environment:
      - KOLLA_CONFIG_STRATEGY=COPY_ONCE
      - KOLLA_CONFIG_FILE=/var/lib/kolla/config_files/mdns/config.json
    networks:
      designate:
        ipv4_address: 10.255.255.70
    depends_on:
      - mysql
      - rabbitmq
      - redis

  designate-worker:
    image: kolla/ubuntu-binary-designate-worker:victoria
    volumes:
      - ./worker:/var/lib/kolla/config_files/worker/
      - ./conf:/var/lib/kolla/config_files/
    environment:
      - KOLLA_CONFIG_STRATEGY=COPY_ONCE
      - KOLLA_CONFIG_FILE=/var/lib/kolla/config_files/worker/config.json
    networks:
      - designate
    depends_on:
      - mysql
      - rabbitmq
      - redis

  designate-producer:
    image: kolla/ubuntu-binary-designate-producer:victoria
    volumes:
      - ./producer:/var/lib/kolla/config_files/producer/
      - ./conf:/var/lib/kolla/config_files/
    environment:
      - KOLLA_CONFIG_STRATEGY=COPY_ONCE
      - KOLLA_CONFIG_FILE=/var/lib/kolla/config_files/producer/config.json
    networks:
      - designate
    depends_on:
      - mysql
      - rabbitmq
      - redis

  designate-central:
    image: kolla/ubuntu-binary-designate-central:victoria
    volumes:
      - ./central:/var/lib/kolla/config_files/central/
      - ./conf:/var/lib/kolla/config_files/
    environment:
      - KOLLA_CONFIG_STRATEGY=COPY_ONCE
      - KOLLA_CONFIG_FILE=/var/lib/kolla/config_files/central/config.json
    networks:
      - designate
    depends_on:
      - mysql
      - rabbitmq
      - redis

  designate-manage:
    image: kolla/ubuntu-binary-designate-central:victoria
    volumes:
      - ./manager:/var/lib/kolla/config_files/manager/
      - ./conf:/var/lib/kolla/config_files/
    environment:
      - KOLLA_CONFIG_STRATEGY=COPY_ONCE
      - KOLLA_CONFIG_FILE=/var/lib/kolla/config_files/manager/config.json
    networks:
      - designate
    depends_on:
      - mysql
      - rabbitmq
      - redis
      - designate-central

  designate-api:
    image: kolla/ubuntu-binary-designate-api:victoria
    volumes:
      - ./api:/var/lib/kolla/config_files/api/
      - ./conf:/var/lib/kolla/config_files/
    environment:
      - KOLLA_CONFIG_STRATEGY=COPY_ONCE
      - KOLLA_CONFIG_FILE=/var/lib/kolla/config_files/api/config.json
    networks:
      - designate
    depends_on:
      - mysql
      - rabbitmq
      - redis
    ports:
      - 9001:9001

  bind:
    build:
      context: bind
    networks:
      designate:
        ipv4_address: 10.255.255.69

    depends_on:
      - mysql
      - rabbitmq
      - redis

networks:
  designate:
    ipam:
      driver: default
      config:
        - subnet: "10.255.255.0/24"
